foreground: &foreground "#ffffff"
background: &background "default"
backgroundOpaque: &backgroundOpaque "#333333"
red: &red "#e0656b"
orange: &orange "#e47c20"
green: &green "#a7e24c"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *red
  prompt:
    fgColor: *green
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *foreground
    sectionColor: *green
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *green
    buttonFocusFgColor: *foreground
    buttonFocusBgColor: *green
    labelFgColor: *green
    fieldFgColor: *green
  frame:
    border:
      fgColor: *green
      focusColor: *green
    menu:
      fgColor: *green
      keyColor: *foreground
      numKeyColor: *green
    crumbs:
      fgColor: *foreground
      bgColor: *backgroundOpaque
      activeColor: *foreground
    status:
      newColor: *green
      modifyColor: *red
      addColor: *green
      pendingColor: *orange
      errorColor: *red
      highlightcolor: *green
      killColor: *green
      completedColor: *green
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *green
      counterColor: *foreground
      filterColor: *orange
  views:
    charts:
      bgColor: *background
      dialBgColor: *background
      chartBgColor: *backgroundOpaque
      defaultDialColors:
        - *green
        - *red
      defaultChartColors:
        - *green
        - *red
      resourceColors:
        batch/v1/jobs:
          - *green
          - *red
        v1/persistentvolumes:
          - *green
          - *red
        cpu:
          - *green
          - *red
        mem:
          - *green
          - *red
        v1/events:
          - *green
          - *red
        v1/pods:
          - *green
          - *red
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *backgroundOpaque
      cursorBgColor: *green
      markColor: *red
      header:
        fgColor: *foreground
        bgColor: *backgroundOpaque
        sorterColor: *green
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *green
      cursorTextColor: *foreground
      graphicColor: *green
    yaml:
      keyColor: *orange
      colonColor: *orange
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *background
